[versions]
# -- toolchain --
agp = "9.0.1"
kotlin = "2.4.10"
ksp = "2.3.12"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"

# -- shared --
coroutines = "1.10.2"
serialization = "1.11.0"
ktor = "3.5.2"
room = "2.8.5"
sqlite = "2.7.1"
datastore = "1.2.1"
okio = "3.18.2"
koin = "4.2.2"
kmpNativeCoroutines = "1.0.5"

# -- android app --
androidx-activity = "1.12.4"
androidx-core = "1.17.0"
androidx-lifecycle = "2.10.0"
composeBom = "2024.09.00"
coil = "3.1.0"
navigation3 = "1.0.1"

# -- quality --
detekt = "1.23.8"

[libraries]
# -- shared: coroutines / serialization --
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

# -- android app--
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-runtimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling" }
compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }

## -- quality --
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt"}

## -- build-logic --
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin  = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin     = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidKmpLibrary   = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt              = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
