complexity:
  LongParameterList:
    ignoreDefaultParameters: true
    ignoreAnnotated:
      - "Composable"

exceptions:
  TooGenericExceptionCaught:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated:
      - "Composable"
  TopLevelPropertyNaming:
    constantPattern: "[A-Z][_A-Za-z0-9]*"

style:
  MagicNumber:
    ignoreNumbers:
      - "-1"
      - "0"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "401"
      - "403"
      - "408"
      - "500"
      - "504"
      - "599"
    ignorePropertyDeclaration: true
    ignoreAnnotated:
      - "Composable"
  UnusedPrivateMember:
    ignoreAnnotated:
      - "Preview"
